# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: connect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rconnect.proto\"r\n\x12\x44\x41ppConnectCommand\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0e\n\x06\x44\x41ppID\x18\x02 \x01(\t\x12\x11\n\tTimestamp\x18\x03 \x01(\x04\x12\x11\n\tSignature\x18\x04 \x01(\t\x12\x16\n\x0eValidatePubKey\x18\x05 \x01(\t\"k\n\x0f\x44\x41ppConnectResp\x12\x0e\n\x06NodeID\x18\x01 \x01(\t\x12\x0e\n\x06\x44\x41ppID\x18\x02 \x01(\t\x12\x11\n\tTimestamp\x18\x03 \x01(\x04\x12\x12\n\nStatusCode\x18\x04 \x01(\x05\x12\x11\n\tStatusMsg\x18\x05 \x01(\tb\x06proto3')



_DAPPCONNECTCOMMAND = DESCRIPTOR.message_types_by_name['DAppConnectCommand']
_DAPPCONNECTRESP = DESCRIPTOR.message_types_by_name['DAppConnectResp']
DAppConnectCommand = _reflection.GeneratedProtocolMessageType('DAppConnectCommand', (_message.Message,), {
  'DESCRIPTOR' : _DAPPCONNECTCOMMAND,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:DAppConnectCommand)
  })
_sym_db.RegisterMessage(DAppConnectCommand)

DAppConnectResp = _reflection.GeneratedProtocolMessageType('DAppConnectResp', (_message.Message,), {
  'DESCRIPTOR' : _DAPPCONNECTRESP,
  '__module__' : 'connect_pb2'
  # @@protoc_insertion_point(class_scope:DAppConnectResp)
  })
_sym_db.RegisterMessage(DAppConnectResp)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DAPPCONNECTCOMMAND._serialized_start=17
  _DAPPCONNECTCOMMAND._serialized_end=131
  _DAPPCONNECTRESP._serialized_start=133
  _DAPPCONNECTRESP._serialized_end=240
# @@protoc_insertion_point(module_scope)
