# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"\x9e\x03\n\x13Web3MQCommonMessage\x12\x0f\n\x07payload\x18\x01 \x01(\x0c\x12\x14\n\x0c\x63ontentTopic\x18\x02 \x01(\t\x12\x0f\n\x07version\x18\x03 \x01(\r\x12\x10\n\x08\x63omeFrom\x18\x04 \x01(\t\x12\x10\n\x08\x66romSign\x18\x05 \x01(\t\x12\x13\n\x0bpayloadType\x18\x06 \x01(\t\x12\x13\n\x0b\x63ipherSuite\x18\x07 \x01(\t\x12\x11\n\tneedStore\x18\x08 \x01(\x08\x12\x11\n\ttimestamp\x18\t \x01(\x04\x12\x11\n\tmessageId\x18\n \x01(\t\x12\x13\n\x0bmessageType\x18\x0b \x01(\t\x12\x0e\n\x06nodeId\x18\x0c \x01(\t\x12\x16\n\x0evalidatePubKey\x18\r \x01(\t\x12\x36\n\textraData\x18\x0e \x03(\x0b\x32#.Web3MQCommonMessage.ExtraDataEntry\x12\x10\n\x08threadId\x18\x0f \x01(\t\x12\x0f\n\x07replyId\x18\x10 \x01(\t\x1a\x30\n\x0e\x45xtraDataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\xf3\x01\n\x0bMessageItem\x12\x11\n\tmessageId\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\r\x12\x0f\n\x07payload\x18\x03 \x01(\x0c\x12\x13\n\x0bpayloadType\x18\x04 \x01(\t\x12\x10\n\x08\x63omeFrom\x18\x05 \x01(\t\x12\x10\n\x08\x66romSign\x18\x06 \x01(\t\x12\x14\n\x0c\x63ontentTopic\x18\x07 \x01(\t\x12\x13\n\x0b\x63ipherSuite\x18\x08 \x01(\t\x12\x11\n\ttimestamp\x18\t \x01(\x04\x12\x0c\n\x04read\x18\n \x01(\x08\x12\x15\n\rreadTimestamp\x18\x0b \x01(\x04\x12\x13\n\x0bmessageType\x18\x0c \x01(\t\"7\n\x19Web3MQMessageListResponse\x12\x1a\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x0c.MessageItemb\x06proto3')



_WEB3MQCOMMONMESSAGE = DESCRIPTOR.message_types_by_name['Web3MQCommonMessage']
_WEB3MQCOMMONMESSAGE_EXTRADATAENTRY = _WEB3MQCOMMONMESSAGE.nested_types_by_name['ExtraDataEntry']
_MESSAGEITEM = DESCRIPTOR.message_types_by_name['MessageItem']
_WEB3MQMESSAGELISTRESPONSE = DESCRIPTOR.message_types_by_name['Web3MQMessageListResponse']
Web3MQCommonMessage = _reflection.GeneratedProtocolMessageType('Web3MQCommonMessage', (_message.Message,), {

  'ExtraDataEntry' : _reflection.GeneratedProtocolMessageType('ExtraDataEntry', (_message.Message,), {
    'DESCRIPTOR' : _WEB3MQCOMMONMESSAGE_EXTRADATAENTRY,
    '__module__' : 'message_pb2'
    # @@protoc_insertion_point(class_scope:Web3MQCommonMessage.ExtraDataEntry)
    })
  ,
  'DESCRIPTOR' : _WEB3MQCOMMONMESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Web3MQCommonMessage)
  })
_sym_db.RegisterMessage(Web3MQCommonMessage)
_sym_db.RegisterMessage(Web3MQCommonMessage.ExtraDataEntry)

MessageItem = _reflection.GeneratedProtocolMessageType('MessageItem', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGEITEM,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:MessageItem)
  })
_sym_db.RegisterMessage(MessageItem)

Web3MQMessageListResponse = _reflection.GeneratedProtocolMessageType('Web3MQMessageListResponse', (_message.Message,), {
  'DESCRIPTOR' : _WEB3MQMESSAGELISTRESPONSE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:Web3MQMessageListResponse)
  })
_sym_db.RegisterMessage(Web3MQMessageListResponse)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WEB3MQCOMMONMESSAGE_EXTRADATAENTRY._options = None
  _WEB3MQCOMMONMESSAGE_EXTRADATAENTRY._serialized_options = b'8\001'
  _WEB3MQCOMMONMESSAGE._serialized_start=18
  _WEB3MQCOMMONMESSAGE._serialized_end=432
  _WEB3MQCOMMONMESSAGE_EXTRADATAENTRY._serialized_start=384
  _WEB3MQCOMMONMESSAGE_EXTRADATAENTRY._serialized_end=432
  _MESSAGEITEM._serialized_start=435
  _MESSAGEITEM._serialized_end=678
  _WEB3MQMESSAGELISTRESPONSE._serialized_start=680
  _WEB3MQMESSAGELISTRESPONSE._serialized_end=735
# @@protoc_insertion_point(module_scope)
